# Generated by Django 4.1.2 on 2022-10-15 22:59

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "user_type",
                    models.CharField(
                        choices=[(1, "Admin"), (2, "Student")], default=2, max_length=20
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=13, null=True)),
                (
                    "personalEmail",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female")], max_length=20
                    ),
                ),
                (
                    "profile_pic",
                    models.ImageField(
                        blank=True, null=True, upload_to="images/Students/profile/"
                    ),
                ),
                ("dob", models.DateField()),
                ("isSelected", models.BooleanField(default=False)),
                ("homeAddress", models.TextField(blank=True, null=True)),
                ("localAddress", models.TextField(blank=True, null=True)),
                (
                    "jobType",
                    models.CharField(
                        choices=[
                            ("Intern", "Internship"),
                            ("Placements", "Placements"),
                        ],
                        max_length=20,
                    ),
                ),
                ("isPR", models.BooleanField(default=False)),
                ("fatherName", models.CharField(blank=True, max_length=255, null=True)),
                ("motherName", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "guardianPhone",
                    models.CharField(blank=True, max_length=13, null=True),
                ),
                ("roll", models.CharField(max_length=9, unique=True)),
                (
                    "degreeLevel",
                    models.CharField(
                        choices=[("UG", "UG"), ("PG", "PG")], max_length=20
                    ),
                ),
                ("currentDept", models.CharField(max_length=255)),
                ("currentCourse", models.CharField(max_length=255)),
                ("currentCgpa", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "currentCourseGraduationYear",
                    models.DateField(blank=True, null=True),
                ),
                (
                    "class10Percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "class12Percentage",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                ("ugDegree", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "ugCgpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("ugCollege", models.CharField(blank=True, max_length=500, null=True)),
                ("ugGraduationYear", models.DateField(blank=True, null=True)),
                (
                    "resume",
                    models.FileField(
                        blank=True, null=True, upload_to="PDF/Students/resume/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
