# Generated by Django 4.1.2 on 2022-10-14 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[(1, 'Admin'), (2, 'Student')], default=1, max_length=20),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.CharField(max_length=9, unique=True)),
                ('dept', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('graduationYear', models.DateField()),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=2)),
                ('resume', models.FileField(blank=True, null=True, upload_to='PDF/Students/resume/')),
                ('isPR', models.BooleanField(default=False)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=20)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='images/Students/profile/')),
                ('phone', models.CharField(max_length=13)),
                ('dob', models.DateField()),
                ('homeAddress', models.TextField()),
                ('localAddress', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
