# Generated by Django 4.1.2 on 2022-10-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_user_type_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="isSelected",
            field=models.BooleanField(default=False),
        ),
    ]
