# Generated by Django 4.1.2 on 2022-10-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_remove_student_class10percentage_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="resume",
        ),
        migrations.AddField(
            model_name="educationdetails",
            name="resume",
            field=models.FileField(
                blank=True, null=True, upload_to="PDF/Students/resume/f{student}"
            ),
        ),
    ]
