# Generated by Django 4.1.2 on 2022-10-15 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_remove_student_resume_educationdetails_resume"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="profile_pic",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/Students/profile/f{student}"
            ),
        ),
    ]
