# Generated by Django 4.1.2 on 2022-10-15 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_alter_student_profile_pic"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="profile_pic",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="images/Students/profile/<django.db.models.fields.related.OneToOneField>",
            ),
        ),
    ]
