# Generated by Django 4.1.2 on 2022-10-15 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0010_alter_educationdetails_resume_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="educationdetails",
            name="ugCgpa",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="educationdetails",
            name="ugCollage",
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name="educationdetails",
            name="ugDegree",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="educationdetails",
            name="ugGraduationYear",
            field=models.DateField(blank=True, null=True),
        ),
    ]
