# Generated by Django 4.1.2 on 2022-10-14 19:31

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("ctc", models.CharField(max_length=10)),
                ("profile", models.CharField(max_length=255)),
                ("company", models.CharField(max_length=255)),
                (
                    "location",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=500), size=None
                    ),
                ),
            ],
        ),
    ]
