# Generated by Django 4.1.2 on 2022-10-14 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job", name="location", field=models.CharField(max_length=500),
        ),
    ]
