# Generated by Django 4.1.2 on 2022-10-16 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="open",
            new_name="opens",
        ),
    ]
