# Generated by Django 4.1.2 on 2022-10-16 02:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_rename_open_job_opens"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 16, 7, 34, 57, 373474)
            ),
        ),
    ]
