# Generated by Django 4.1.2 on 2022-10-14 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_alter_job_location"),
    ]

    operations = [
        migrations.RemoveField(model_name="job", name="role",),
        migrations.AddField(
            model_name="job", name="open", field=models.BooleanField(default=False),
        ),
    ]
