# Generated by Django 4.1.2 on 2022-10-16 02:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_job_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="deadline",
            field=models.DateTimeField(
                default=datetime.datetime(2022, 10, 16, 7, 35, 11, 40143)
            ),
        ),
    ]
