# Generated by Django 4.1.2 on 2022-10-16 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_job_deadline"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="deadline",
            field=models.DateTimeField(),
        ),
    ]
